packages:
  - apps/*
  - packages/*
  - toolings/*

catalog:
  "@tanstack/react-query": ^5.62.9
  "@tanstack/react-query-devtools": ^5.62.11
  "@trpc/client": ^11.0.0-rc.666
  "@trpc/react-query": ^11.0.0-rc.666
  "@trpc/server": ^11.0.0-rc.666
  dotenv-cli: "^7.4.4"
  eslint: ^9.17.0
  prettier: ^3.4.2
  superjson: ^2.2.2
  tailwindcss: ^3.4.17
  typescript: ^5.7.2
  zod: ^3.24.1

catalogs:
  "supabase":
    "@supabase/ssr": "^0.5.2"
    "@supabase/supabase-js": "^2.47.10"
    "supabase": "^1.226.4"
    "supabase-to-zod": "^1.0.7"

  "next15/react19":
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.2
    "@types/react-dom": ^19.0.2

  "next15/react19-compiler":
    next: 15.1.1-canary.18
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.2
    "@types/react-dom": ^19.0.2

  "next15/react18":
    next: 15.1.2
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
