import type { Metadata, Viewport } from "next";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";

import "~/app/globals.css";

import type { PropsWithChildren } from "react";

import { ThemeProvider } from "@embed-stuff/ui/components/theme-provider";
import { cn } from "@embed-stuff/ui/lib/utils";
import { Toaster } from "@embed-stuff/ui/ui/toaster";
import { TooltipProvider } from "@embed-stuff/ui/ui/tooltip";

export const metadata: Metadata = {
  title: "The Emote Kit",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

const Layout = (props: PropsWithChildren) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(GeistSans.variable, GeistMono.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <Toaster />
            <TRPCReactProvider>{props.children}</TRPCReactProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default Layout;
